[book]
authors = ["Joichiro Hayashi"]
language = "en"
src = "src"
title = "Valof"

[preprocessor.sidebar]
command = "node tools/mdbook-sidebar/index.ts"
renderers = ["html"]
default-open = false

[preprocessor.shiki]
command = "node tools/mdbook-shiki/index.ts"
renderers = ["html"]
after = ["links"]
light-theme = "one-light"
dark-theme = "one-dark-pro"
fallback-language = "text"

[output.html]
additional-css = ["tools/mdbook-shiki/shiki.css", "tools/mdbook-sidebar/sidebar.css"]
additional-js = [".generated/mdbook-sidebar/headings.js", "tools/mdbook-sidebar/sidebar.js"]
